# Generated by Django 5.2.4 on 2025-08-01 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='telefono',
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('ocupada', 'Ocupada')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='total_mesas',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='PerfilAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
