# Generated by Django 5.2.4 on 2025-08-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_mesa_disponible_remove_mesa_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_personas',
            field=models.PositiveIntegerField(),
        ),
    ]
