# Generated by Django 5.2.4 on 2025-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_options_alter_reserva_num_personas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['mesa', 'fecha'], name='reservas_re_mesa_id_3edd73_idx'),
        ),
    ]
