# Generated by Django 5.2.4 on 2025-08-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reserva',
            name='reservas_re_mesa_id_3edd73_idx',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('CONF', 'Confirmada'), ('CANC', 'Cancelada'), ('NOSH', 'No show')], default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.mesa'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_personas',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
