# Generated by Django 5.2.4 on 2025-08-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_reserva_reservas_re_mesa_id_3edd73_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='llego',
            field=models.BooleanField(default=False),
        ),
    ]
