# Generated by Django 5.2.4 on 2025-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_checkin_at_reserva_llego'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
