# Generated by Django 5.2.4 on 2025-08-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='creada_por_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='email_contacto',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_contacto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
