# Generated by Django 5.2.4 on 2025-08-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_creada_por_staff_reserva_email_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asistentes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
