# Generated by Django 5.2.4 on 2025-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_reserva_asistentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='asistentes',
        ),
        migrations.AddField(
            model_name='reserva',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_personas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
