# Generated by Django 5.2.4 on 2025-09-12 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_remove_reserva_asistentes_reserva_modificado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='total_mesas',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='administradores',
            field=models.ManyToManyField(blank=True, related_name='sucursales_administra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
