# Generated by Django 5.2.4 on 2025-09-13 19:06

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_populate_sucursal_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='folio',
            field=models.CharField(
                max_length=10,
                null=True,
                blank=True,
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='administradores',
            field=models.ManyToManyField(
                blank=True,
                related_name='sucursales_administradas',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='slug',
            field=models.SlugField(
                default=uuid.uuid4,
                editable=False,
                unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(
                condition=models.Q(('estado__in', ['PEND', 'CONF'])),
                fields=('cliente',),
                name='uniq_reserva_activa_por_cliente',
            ),
        ),
    ]
