# Generated by Django 5.2.4 on 2025-09-16 16:11

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_make_folio_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='uniq_reserva_activa_por_cliente',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='folio',
            field=models.CharField(db_index=True, default=reservas.models.generar_folio, editable=False, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cliente', 'estado'], name='reservas_re_cliente_5b00f2_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha'], name='reservas_re_fecha_92a0c0_idx'),
        ),
    ]
