# Generated by Django 5.2.4 on 2025-09-16 17:06

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_remove_reserva_uniq_reserva_activa_por_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha', '-creado']},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='folio',
            field=models.CharField(db_index=True, default=reservas.models.generar_folio, editable=False, max_length=20, unique=True),
        ),
    ]
