# Generated by Django 5.2.4 on 2025-09-16 21:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_alter_reserva_options_alter_reserva_folio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El código postal debe tener 5 dígitos.', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El código postal debe tener 5 dígitos.', regex='^\\d{5}$')]),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['codigo_postal'], name='reservas_su_codigo__735b1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(fields=('sucursal', 'numero'), name='uniq_mesa_por_sucursal'),
        ),
    ]
