# Generated by Django 5.2.4 on 2025-09-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_alter_cliente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='reservas.mesa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='reservas.sucursal')),
            ],
            options={
                'verbose_name': 'Bloqueo de mesa',
                'verbose_name_plural': 'Bloqueos de mesa',
                'indexes': [models.Index(fields=['sucursal', 'inicio'], name='reservas_bl_sucursa_d4e6b1_idx'), models.Index(fields=['sucursal', 'fin'], name='reservas_bl_sucursa_e96a67_idx'), models.Index(fields=['inicio', 'fin'], name='reservas_bl_inicio_130a3d_idx')],
            },
        ),
    ]
