# Generated by Django 5.2.4 on 2025-09-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_mesa_notas_mesa_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['-recomendado', 'nombre']},
        ),
        migrations.AddField(
            model_name='sucursal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='cocina',
            field=models.CharField(blank=True, default='Americana • Desayunos', max_length=80),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='portada',
            field=models.ImageField(blank=True, help_text='Imagen 16:9 recomendada', null=True, upload_to='sucursales/portadas/'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='portada_alt',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='precio_nivel',
            field=models.CharField(blank=True, default='$$', help_text='Usa $, $$, $$$, $$$$', max_length=10),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
