# Generated by Django 5.2.4 on 2025-09-27 19:17

import django.db.models.deletion
import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_alter_sucursal_options_sucursal_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[reservas.models.cp_mx_validator]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[reservas.models.cp_mx_validator]),
        ),
        migrations.CreateModel(
            name='SucursalFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='sucursales/galeria/')),
                ('alt', models.CharField(blank=True, default='', max_length=140, verbose_name='Texto alternativo')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='reservas.sucursal')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
