# Generated by Django 5.2.4 on 2025-09-27 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_alter_cliente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalfoto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursalfoto',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
