# Generated by Django 5.2.4 on 2025-09-27 22:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_sucursalfoto_activo_sucursalfoto_creado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloqueomesa',
            options={'ordering': ['-inicio'], 'verbose_name': 'Bloqueo de mesa', 'verbose_name_plural': 'Bloqueos de mesa'},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['sucursal', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'permissions': [('view_all_sucursales', 'Puede ver todas las sucursales activas')]},
        ),
        migrations.RemoveIndex(
            model_name='sucursal',
            name='reservas_su_codigo__735b1b_idx',
        ),
        migrations.RemoveField(
            model_name='sucursalfoto',
            name='activo',
        ),
        migrations.AddField(
            model_name='mesa',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='perfiladmin',
            name='sucursal_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins_principales', to='reservas.sucursal'),
        ),
        migrations.AlterField(
            model_name='perfiladmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfiladmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='administradores',
            field=models.ManyToManyField(blank=True, related_name='sucursales_que_administra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cocina',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='sucursales/portadas/'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='portada_alt',
            field=models.CharField(blank=True, max_length=120),
        ),

        # 🔧 FIX: normalizar valores de precio_nivel ANTES de cambiar el tipo
        migrations.RunSQL(
            """
            UPDATE reservas_sucursal
            SET precio_nivel = CASE
                WHEN precio_nivel IS NULL        THEN '1'
                WHEN precio_nivel IN ('1','2','3') THEN precio_nivel
                WHEN precio_nivel = '$'          THEN '1'
                WHEN precio_nivel = '$$'         THEN '2'
                WHEN precio_nivel = '$$$'        THEN '3'
                WHEN precio_nivel = '$$$$'       THEN '3'
                WHEN precio_nivel = ''           THEN '1'
                ELSE '1'
            END;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name='sucursal',
            name='precio_nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], default=1),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='sucursalfoto',
            name='alt',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sucursalfoto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
