# Generated by Django 5.2.4 on 2025-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_menucategoria_menuitem_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='liberada_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
