# Generated by Django 5.2.4 on 2025-09-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_reserva_liberada_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={},
        ),
    ]
