# Generated by Django 5.2.7 on 2025-10-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0027_alter_mesa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
