# Generated by Django 5.2.7 on 2025-10-07 15:44

import django.db.models.deletion
import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0028_alter_sucursal_nombre_alter_sucursal_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['sucursal', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'permissions': [('manage_branches', 'Puede administrar/visualizar todas las sucursales')]},
        ),
        migrations.AddField(
            model_name='reserva',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.sucursal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='folio',
            field=models.CharField(db_index=True, default=reservas.models.generar_folio, editable=False, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['mesa', 'fecha'], name='reservas_re_mesa_id_3edd73_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['sucursal', 'fecha'], name='reservas_re_sucursa_c61bb8_idx'),
        ),
    ]
