# Generated by Django 5.2.7 on 2025-10-07 16:50

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0030_alter_reserva_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='folio',
            field=models.CharField(db_index=True, default=reservas.models.generar_folio, editable=False, max_length=20, unique=True),
        ),
    ]
