# Generated by Django 5.2.7 on 2025-10-07 17:46

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0031_alter_reserva_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='pos_x',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje X 0..100'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='pos_y',
            field=models.PositiveSmallIntegerField(default=0, help_text='Porcentaje Y 0..100'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='folio',
            field=models.CharField(db_index=True, default=reservas.models.generar_folio, editable=False, max_length=20, unique=True),
        ),
    ]
