# Generated by Django 5.2.7 on 2025-10-07 18:59

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0032_mesa_pos_x_mesa_pos_y_alter_reserva_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='zona',
            field=models.CharField(choices=[('interior', 'Interior'), ('terraza', 'Terraza'), ('exterior', 'Exterior')], db_index=True, default='interior', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='folio',
            field=models.CharField(db_index=True, default=reservas.models.generar_folio, editable=False, max_length=20, unique=True),
        ),
    ]
