# Generated by Django 5.2.7 on 2025-10-07 21:39

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0033_mesa_zona_alter_reserva_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalfoto',
            name='recepcion_x',
            field=models.PositiveSmallIntegerField(default=3, help_text='Porcentaje X 0..100 para la recepción'),
        ),
        migrations.AddField(
            model_name='sucursalfoto',
            name='recepcion_y',
            field=models.PositiveSmallIntegerField(default=3, help_text='Porcentaje Y 0..100 para la recepción'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='folio',
            field=models.CharField(db_index=True, default=reservas.models.generar_folio, editable=False, max_length=20, unique=True),
        ),
    ]
