# Generated by Django 5.2.7 on 2025-10-11 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0036_sucursal_lat_sucursal_lng_sucursal_place_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainOwnerPaisRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Administrador País (ChainOwner)',
                'verbose_name_plural': 'Administradores País (ChainOwners)',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='fin_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='inicio_utc',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='local_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='local_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='local_service_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA TZ (ej. America/Mexico_City)', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['inicio_utc'], name='reservas_re_inicio__5d7f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['local_service_date'], name='reservas_re_local_s_b018fd_idx'),
        ),
        migrations.AddField(
            model_name='chainownerpaisrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_pais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chainownerpaisrole',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chainowners', to='reservas.pais'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='reservas.pais'),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['pais'], name='reservas_su_pais_id_e640c1_idx'),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['timezone'], name='reservas_su_timezon_8ea7a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chainownerpaisrole',
            unique_together={('user', 'pais')},
        ),
    ]
