# Generated by Django 5.2.4 on 2025-10-16 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0037_chainownerpaisrole_pais_reserva_fin_utc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='CountryAdminScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_admins', to='reservas.pais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ámbito de país (admin)',
                'verbose_name_plural': 'Ámbitos de país (admins)',
                'unique_together': {('user', 'pais')},
            },
        ),
    ]
