# Generated by Django 5.2.4 on 2025-11-03 16:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0038_sucursal_email_contacto_countryadminscope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada a cocina'), ('IN_PREP', 'En preparación'), ('READY', 'Lista'), ('SERVED', 'Servida'), ('CLOSED', 'Cerrada')], default='DRAFT', max_length=20)),
                ('iva_rate', models.DecimalField(decimal_places=2, default=Decimal('0.16'), max_digits=4)),
                ('propina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_con_propina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('NONE', 'Sin pago'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('MIXED', 'Mixto')], default='NONE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_cerrados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_creados', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='reservas.mesa')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='reservas.reserva')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='reservas.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('notas', models.CharField(blank=True, default='', max_length=240)),
                ('enviado_a_cocina', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.order')),
            ],
        ),
    ]
