# Generated by Django 5.2.4 on 2025-11-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0039_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de menú',
                'verbose_name_plural': 'Categorías de menú',
                'db_table': 'catalog_category',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True, verbose_name='Código (identificador)')),
                ('nombre', models.CharField(max_length=180, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('area_impresion', models.CharField(choices=[('cocina', 'Cocina'), ('bebidas', 'Bebidas'), ('postres', 'Postres')], default='cocina', max_length=12, verbose_name='Área de impresión')),
                ('imprimible', models.BooleanField(default=True, verbose_name='Imprimible en cocina')),
                ('es_combo', models.BooleanField(default=False, verbose_name='Es combo')),
                ('precio_combo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Precio del combo (si fijo)')),
                ('aplica_impuesto', models.BooleanField(default=True, verbose_name='Aplica impuesto')),
                ('aplica_servicio', models.BooleanField(default=False, verbose_name='Aplica cargo por servicio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reservas.catalogcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ítem de menú',
                'verbose_name_plural': 'Ítems de menú',
                'db_table': 'catalog_item',
                'ordering': ['categoria__orden', 'categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatalogComboComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('combo', models.ForeignKey(limit_choices_to={'es_combo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='reservas.catalogitem', verbose_name='Combo')),
                ('item', models.ForeignKey(limit_choices_to={'es_combo': False}, on_delete=django.db.models.deletion.PROTECT, related_name='incluido_en_combos', to='reservas.catalogitem', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Componente de combo',
                'verbose_name_plural': 'Componentes de combo',
                'db_table': 'catalog_combo_component',
            },
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['codigo'], name='catalog_ite_codigo_3aa0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['nombre'], name='catalog_ite_nombre_6bb492_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['activo'], name='catalog_ite_activo_1639ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogcombocomponent',
            unique_together={('combo', 'item')},
        ),
    ]
