# Generated by Django 5.2.4 on 2025-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0041_orden_ordenitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='recepcion_x',
            field=models.PositiveSmallIntegerField(default=3, help_text='Porcentaje X 0..100'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='recepcion_y',
            field=models.PositiveSmallIntegerField(default=3, help_text='Porcentaje Y 0..100'),
        ),
    ]
