# Generated by Django 5.2.4 on 2025-11-06 23:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0042_alter_sucursal_recepcion_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='precio_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
