# Generated by Django 5.2.4 on 2025-11-21 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0043_ordenitem_precio_alter_ordenitem_precio_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenitem',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREP', 'En preparación'), ('SERVIDO', 'Servido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.catalogitem'),
        ),
    ]
